In [16]:
import numpy as np

In [3]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.randint(1,10,50)

array([9, 7, 9, 4, 1, 3, 3, 9, 9, 3, 4, 6, 5, 2, 5, 5, 8, 4, 5, 2, 6, 4,
       2, 4, 4, 5, 4, 6, 3, 9, 4, 4, 2, 1, 8, 9, 2, 7, 5, 9, 4, 7, 3, 5,
       7, 8, 6, 3, 1, 8], dtype=int32)

In [7]:
np.random.rand(7)

array([0.93148736, 0.38854593, 0.36053035, 0.57204668, 0.74566841,
       0.67280575, 0.10331314])

In [8]:
np.random.randn(10)

array([ 0.78087798,  0.41744954, -0.05481517, -0.67810525,  0.30785433,
        0.33393505,  1.73185292,  0.13098155,  0.5071048 , -1.64397363])

In [9]:
arr = np.array([10,20,30,40])
arr1 = arr.copy()
print(id(arr))
print(id(arr1))
arr1[0]=900
arr1
arr
#addresses are different and changes are not reflected 

1737301167056
1737301165616


array([10, 20, 30, 40])

In [10]:
arr = np.array([10,20,30,40])
arr1 = arr.view()
print(id(arr))
print(id(arr1))
arr1[0]=900
print(arr1)
print(arr)
#addresses are different but changes are reflected

1737301166960
1737301167440
[900  20  30  40]
[900  20  30  40]


In [11]:
arr = np.array([45,46,47,48,49])
arr[-4]


np.int64(46)

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0]
arr[1:][1][1:]

array([10, 11, 12])

In [13]:
#Indexing and slicing on array

In [14]:
#1D Array
#indexing
arr = np.array([100,101,102,103,104])
arr[0]
arr[-5]
#slicing
arr[::2]

array([100, 102, 104])

In [21]:
#2D array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
arr[1]


array([5, 6, 7, 8])

In [26]:
#slicing
arr[0:3:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
#indexing slicing both